### PR TITLE
docs: complete 4-4.md

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by mancuoj** [comment]
.... 所以我合并的太早了？你还没完成是吧

**Comment by mancuoj** [comment]
https://github.com/csfive/composing-programs-zh/commit/b35233b1859ecf06c107134424ce0308e6843bc8  

无所谓你 git pull 继续提交吧，尽量遵守一下规范好吧，可以看一下我几分钟修改的部分。

**Comment by mancuoj** [comment]
> > [b35233b](https://github.com/csfive/composing-programs-zh/commit/b35233b1859ecf06c107134424ce0308e6843bc8)
> > 无所谓你 git pull 继续提交吧，尽量遵守一下规范好吧，可以看一下我几分钟修改的部分。
> 
> 非常抱歉，我PR之后，看了一下检查结果，发现没有带标题 ## 符号。

最好按要求再改一遍，要不我没法合并的，可以再看一遍那个排版指南 😊😊

**Comment by alikhan4007** [comment]
I am writing to bring to your attention a repository that is in violation of the Harvard Honesty Policy. The repository in question, named [cs50], contains materials that are against the principles of academic integrity and compromise the reputation of our institution.

Upon thorough investigation, it has come to my attention that Cs50 hosts numerous academic resources that are intended to be private or are protected by copyright. The presence of these materials in a publicly accessible repository goes against the Harvard Honesty Policy, which encourages the respectful and responsible use of intellectual property.

I kindly request that immediate action be taken to address this issue. There are two possible courses of action that could rectify the situation:

Make the Repository Private: The repository should be set to private access only, limiting the availability of the materials to authorized individuals such as course instructors, students, or researchers. This measure will help ensure compliance with the Harvard Honesty Policy while still allowing for appropriate educational use.

Removal of the Repository: If making the repository private is not feasible or sufficient, I strongly urge you to take steps to remove the repository entirely from the hosting platform. This will prevent further misuse of the materials and discourage future violations of the Harvard Honesty Policy.

I understand the importance of promoting academic integrity and maintaining the reputation of our institution. It is crucial that we address such violations promptly and effectively. By taking action against repositories that facilitate the unauthorized distribution of academic resources, we demonstrate our commitment to upholding the principles of honesty and ethical conduct at Harvard.

I appreciate your attention to this matter and your commitment to maintaining a high standard of academic integrity. Please keep me informed of the actions taken to resolve this issue. If you require any additional information or assistance, please do not hesitate to contact me.

**Comment by alikhan4007** [comment]
I am writing to bring to your attention a repository that is in violation of the Harvard Honesty Policy. The repository in question, named [cs50], contains materials that are against the principles of academic integrity and compromise the reputation of our institution.

Upon thorough investigation, it has come to my attention that Cs50 hosts numerous academic resources that are intended to be private or are protected by copyright. The presence of these materials in a publicly accessible repository goes against the Harvard Honesty Policy, which encourages the respectful and responsible use of intellectual property.

I kindly request that immediate action be taken to address this issue. There are two possible courses of action that could rectify the situation:

Make the Repository Private: The repository should be set to private access only, limiting the availability of the materials to authorized individuals such as course instructors, students, or researchers. This measure will help ensure compliance with the Harvard Honesty Policy while still allowing for appropriate educational use.

Removal of the Repository: If making the repository private is not feasible or sufficient, I strongly urge you to take steps to remove the repository entirely from the hosting platform. This will prevent further misuse of the materials and discourage future violations of the Harvard Honesty Policy.

I understand the importance of promoting academic integrity and maintaining the reputation of our institution. It is crucial that we address such violations promptly and effectively. By taking action against repositories that facilitate the unauthorized distribution of academic resources, we demonstrate our commitment to upholding the principles of honesty and ethical conduct at Harvard.

I appreciate your attention to this matter and your commitment to maintaining a high standard of academic integrity. Please keep me informed of the actions taken to resolve this issue. If you require any additional information or assistance, please do not hesitate to contact me.

**Pull request closed without merging**
